### ISSUE TITLE
What you need for this book...

### ISSUE THREAD

**Issue by bucweat** [PacktPublishing/PythonDataAnalysisCookbook#1]
Purchased your book the other day and starting to work through it. Would have been nice to have a packages.txt or requirements.txt file with the packages recommended on pages xi and xii. Even better would be a list of packages with version numbers that have resolved dependencies, since that is a main topic of the book. Maybe it comes later...I'm still in chapter 1. Maybe dependencies are different in Anaconda vs miniconda, which is what I have installed?

 I used "conda create --name PDAC --file packages.txt" where packages.txt was built from the list of packages on xi and xii. However, with the version numbers listed and Python 3.4.5 I couldn't get all the dependencies to resolve, and so I had to play a bit (entries with wildcard \* at the end) to find combination that worked. I hopefully have attached what worked for me.

Also, install_ch1.py needs a few extra packages added in order to run chapter 1 scripts successfully. Since these didn't show up in conda I added them in this script to install via pip:

```
install('bs4')
install('zmq')
install('selenium')
```

Charlie
[packages.txt](https://github.com/PacktPublishing/PythonDataAnalysisCookbook/files/535223/packages.txt)

**Comment by techsachinkumar** [comment]
Added the packages.txt file

Regards
