### ISSUE TITLE
google drive link in dautil is broke

### ISSUE THREAD

**Issue by bucweat** [PacktPublishing/PythonDataAnalysisCookbook#2]
line 215 in report.py: https://www.googledrive.com/host/0B8Dd5LtC555uNTJQXzZKdDN4aWc

Google I think changed their URL scheme for their entire site. I'm guessing the link should look more like https://drive.google.com/drive/folders/... so this probably requires an update.

**Comment by aoshiliang** [comment]
> line 215 in report.py: https://www.googledrive.com/host/0B8Dd5LtC555uNTJQXzZKdDN4aWc
> 
> Google I think changed their URL scheme for their entire site. I'm guessing the link should look more like https://drive.google.com/drive/folders/... so this probably requires an update.

Yes, this code and cookbook has already lag-behind, packages like dautil have many bugs during my project. I have already ignore the environment written by the author. Only some of the code can be used in some other place.
